version: '1'
services:
  motion:
    image: motionproject/motion:latest
    container_name: motion
    ports:
      - 17999:7999
      - 18081:8081
      - 18082:8082
      - 18083:8083
      - 18084:8084
      - 18085:8085
      - 18087:8087
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/motion/config:/etc/motion
      - /volume1/motion/storage:/var/lib/motion
    restart: always
