version: '3.3'
services:
  motion:
    image: motionproject/motion:latest
    container_name: motion
    ports:
      - 18080:8080
      - 18081:8081
      - 18082:8082
      - 18083:8083
      - 18084:8084
      - 18085:8085
      - 18087:8087
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/motion/config:/usr/local/etc/motion
      - /volume1/motion/storage:/var/lib/motion
      - /volume1/motion/logs:/var/log/motion
    restart: always
